# Konfigurasi Continuos Deployment
name: 3_warehouse

on:
  push:
    branches:
      - dev

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy 3_warehouse API with github action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: 22
          script: |
            cd ~/app/3-warehouse-api
            git pull origin dev
            npm install
            pm2 restart 3-warehouse
