# Konfigurasi Continuos Deployment
name: 3_warehouse

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy 3_warehouse API with github action
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.115.129
          username: "root"
          password: "PurwadhikaJCWD;"
          port: 22
          script: |
            cd ~/app/jcfs-1904-group3-be
            git pull origin master
            npm install
            pm2 restart api-3-warehouse
